### ISSUE TITLE
What's the license of this project?

### ISSUE THREAD

**Issue by Aleksanaa** [ppvan/pg_query_vala#1]

**Comment by ppvan** [comment]
Maybe extends from upstream?
I'm bad at license...
Btw, project exist because I'm can't figure out how to config meson and bind vapi correctly. I'm not really think about it

Check [this](https://github.com/pganalyze/libpg_query?tab=readme-ov-file#license)

**Comment by Aleksanaa** [comment]
The BSD license does not propagate, you should still choose a license yourself. Otherwise, other people who package or want to contribute source code may be confused.

**Comment by ppvan** [comment]
> The BSD license does not propagate, you should still choose a license yourself.

So I can choose any thing? Let's go with GPLv3

And in the future I probably replace this with [postgres_lsp](https://github.com/supabase/postgres_lsp) (Which still use pg_query underthehood)

Thank you, I'll include the license rightaway

**Comment by Aleksanaa** [comment]
> Let's go with GPLv3

Okay, last question, GPLv3 only or including any later versions?

**Comment by ppvan** [comment]
Any later versions

https://github.com/ppvan/pg_query_vala/blob/main/LICENSE
